import { createContext } from "react";

const data = [
  {
    id: 1,
    title: "What a scientist has claimed about finding ‘alien life’, and why his peers are irked",
    post_date: "July 25 2023",
    genre: "Technology",
    ref: 'https://indianexpress.com/article/explained/explained-sci-tech/scientist-claiming-to-have-found-alien-irked-peers-8859721/',
    thumb:
      "https://images.indianexpress.com/2023/07/SCI-ASTROPHYSICIST-ALIENS.jpg?w=640",
    desciption:
      "For much of his career, Loeb has been a powerhouse of a cosmologist, churning out hundreds of papers on black holes, dark matter, and the first stars. But he has been captivated by the search for aliens since an interstellar object named Oumuamua zoomed by our planet in 2017. Here's what his latest claims are",
      detail: "On Jan 8, 2014, a fireball from space blazed through Earth’s atmosphere and crashed into the sea, north of Manus Island off the northeastern coast of Papua New Guinea. Its location, velocity and brightness were recorded by US government sensors and quietly tucked away in a database of similar events.  That data sat for five years, a source of no contention until Avi Loeb, a theoretical astrophysicist at Harvard University, and Amir Siraj, then an undergraduate student at the university, stumbled across it in 2019. Based on its logged speed and direction, Siraj identified the fireball as an extreme outlier.  Last month, Loeb led an expedition to retrieve fragments of the fireball off the western Pacific seafloor. On June 21, he claimed that he had. And such discoveries, he says to the chagrin of many of his colleagues, may be the way scientists find evidence of extraterrestrial life.  “Not biological creatures, the way you see in science fiction movies,” Loeb said. “It’s most likely a technological gadget with artificial intelligence.”  Many astronomers, though, see the announcement as the latest example of Loeb making an outlandish declaration that is too strong and too hasty. His pronouncements (and a promotional video in Times Square about the search for extraterrestrial life) skew public perception of how science actually works, they say.  “People are sick of hearing about Avi Loeb’s wild claims,” said Steve Desch, an astrophysicist at Arizona State University. “It’s polluting good science — conflating the good science we do with this ridiculous sensationalism and sucking all the oxygen out of the room.”  Desch added that several of his colleagues were now refusing to engage with Loeb’s work in peer review, the process by which scholars evaluate one another’s research to ensure that only high-quality studies are published. “It’s a real breakdown of the peer review process and the scientific method,” he said. “And it’s so demoralizing and tiring.”  For much of his career, Loeb has been a powerhouse of a cosmologist, churning out hundreds of papers on black holes, dark matter, the first stars and the fate of our universe. But he has been captivated by the search for aliens since an interstellar object named Oumuamua zoomed by our planet in 2017. While scientists debated whether that visitor was an asteroid or a comet from another star system, Loeb made the case that it could be an artifact of intelligent life."
  },
  {
    id: 2,
    title: 'AI: How far is China behind the West?',
    post_date: 'July 25 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/explained/explained-sci-tech/ai-how-far-is-china-behind-the-west-8858079/',
    thumb: 'https://images.indianexpress.com/2023/07/AI-China-West.jpg?w=640',
    description: 'China has restated its goal to be the global leader in artificial intelligence (AI). When it comes to snooping on the public, the country has the edge but faces many other hurdles.',
    detail: "Chinese tech giants are speeding to catch up with their US peers in the creation of artificial intelligence (AI) chatbots. The world’s second-largest economy is on course to spend $15 billion (€13.5 billion) on AI projects this year alone, a rise of nearly 50% in just two years.  Even before the arrival of large language models like the Microsoft-backed Chat GPT, some tech experts refused to bet that the West would dominate the AI race, despite the most advanced AI labs being located in the US and UK.  Kai-Fu Lee, the Taiwanese computer scientist, venture capitalist and tech executive predicted in 2018 that China would quickly surpass the US as an AI superpower, insisting the technology had already passed the innovation stage.  Lee argued that the world was now in the AI implementation stage, where China has the edge, due to years of state surveillance. Snooping on the Chinese population has allowed the accrual of huge amounts of data, which AI platforms harness to improve their learning.  But while more than half of the estimated 1 billion surveillance cameras on the planet have been deployed in China, Lee’s critics argue that the AI revolution is still in its infancy and the West still holds the key.  “The big innovations in AI haven’t happened yet — far from it […] and the US currently has the advantage in that area,” Pedro Domingos, professor emeritus at the Paul G. Allen School of Computer Science & Engineering at the University of Washington, told DW.  Domingos spoke of large data having “diminishing returns,” in that China won’t get a lot more benefit from snooping on its 1.4 billion population than the US does, with its 332 million inhabitants.  “The diversity of the data also matters. I would prefer to have the data from, say, Europe than China as it is more diverse and therefore you can learn more from it.”"
  },
  {
    id: 3,
    title: 'OneWeb to set up India’s first ‘satellite network portal site’ in Gujarat: What is the project, its significance?',
    post_date: 'July 23 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/explained/explained-sci-tech/oneweb-india-set-up-first-satellite-network-portal-site-in-gujarat-8854452/',
    thumb: 'https://images.indianexpress.com/2023/07/OneWeb-Gujarat.jpg?w=640',
    description: 'OneWeb India Communications plans to invest up to Rs 100 crore in the project, which would, according to the Gujarat government, create 500 direct and indirect jobs, including jobs requiring telecom, electronics and instrumentation engineers.',
    detail: "The Gujarat government through its Department of Science and Technology (DST) on Wednesday (July 19) signed a memorandum of understanding with OneWeb India Communications Pvt Ltd for setting up a ‘satellite network portal site’ — a first for India — at Mehsana in Gujarat.  Satellite broadband technology or satellite telephony is not a new concept and with satellite constellations in the low Earth orbit (LEO) gaining traction with StarLink, Kuiper and OneWeb among many others, the world is increasingly moving towards relying on LEO satellite communications.  LEO satellites operate at an altitude of 500 to 1,200 km, making it ripe for high-speed and low latency — a lower time lag between a user seeking data, and the server sending that data, compared to geostationary Earth orbit positioned satellites.  OneWeb has 648 satellites orbiting at 1,000-1,200 km making 13 orbits per day, covering the entire globe. The satellite network portal (SNP) site will be serving as a signal and data downlink and uplink terminal or base station on the ground, an intermediary for data transmission through satellite tracking antenna systems.  Rahul Vatts, director of OneWeb India Communications, told The Indian Express, “To cover the entire Earth, we need 40 such SNPs but for India we need at least 2 such SNPs because India is such a large geography and we decided to set up one in Gujarat and another we are planning in the southern part of India, likely to be in Tamil Nadu.”  As per the financial year 2021-2022 annual report of OneWeb, it had nine operational SNP sites serving the live coverage area and at the time, had agreements to build 38 SNPs in 27 different countries."
  },
  {
    id: 4,
    title: 'The story of ISRO’s origins, as Chandrayaan-3 flies to the Moon',
    post_date: 'July 17 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/explained/explained-sci-tech/isro-origin-chandrayaan-3-history-sarabhai-8842095/',
    thumb: 'https://images.indianexpress.com/2023/07/Untitled-design-33.jpg?w=640',
    description: 'India’s space agency was the brainchild of Dr Vikram Sarabhai and has now come to represent a success story. Here’s a brief look at how it began.',
    detail: "Chandrayaan-3, the mission that aims to achieve the feat of conducting a “soft” landing on the Moon’s southern pole, launched off from the Satish Dhawan Space Centre (SDSC) in Andhra Pradesh on Friday (July 14) afternoon.  It will now take approximately 42 days to reach the Moon. Should it conduct a successful landing, India will become only the fourth country – after the United States, Russia, and China – to have done so.  While a successful launch is only the first step towards a long journey for the spacecraft, Isro’s role in carrying it through has seen great appreciation, and it has become a symbol of national pride for many. That has been the case for long, such as in 2014, when the Mars Orbiter Mission (MOM) was inserted into the Martian orbit. The low cost of the mission was also highlighted as an achievement. Since its inception in 1969, the country’s space agency Isro has carried out altogether 89 launch missions carrying satellites into space. How did the agency chart this course? We take a look.  Early beginnings of a space agency, from a church in Kerala  The history of space activities in India reflects how little by little, institutions centred around space exploration and research were set up and expanded. Indian scientist EV Chitnis recounted in the book From Fishing Hamlet to Red Planet: India’s Space Journey, a compilation of essays from those involved in this journey, that the first such organisation was the Physical Research Laboratory set up in Ahmedabad, Gujarat.  Along with Vikram Sarabhai, a few scientists worked here but lacked adequate funds. Chitnis recalls putting together two boxes and an asbestos sheet as his work table."
  },
  {
    id: 5,
    title: 'Electric vehicle tires: a lesser-known pollution headache',
    post_date: 'July 16 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/explained/explained-sci-tech/how-electric-vehicle-tires-cause-pollution-8837699/',
    thumb: 'https://images.indianexpress.com/2023/07/EV-tires-cause-pollution.jpg?w=640',
    description: "The tire industry has been keeping up pace with the rising EV demand, but there is one problem it's struggling to crack.",
    detail: "As EV sales have soared, the tire industry has innovated its products to fit the needs of the relatively heavy, efficient and silent cars. But there is one problem the industry is struggling to crack.  As a car’s only point of contact with the road, tires do more work than they get credit for. Tires need to grip the road firmly enough for cars to accelerate, turn and brake without skidding, but they also need to reduce rolling resistance enough to maintain fuel efficiency.  For tire manufacturers, creating the perfect tire — one that balances performance and durability — is an unending task. In recent years, their work has been further complicated by electric vehicles (EVs).  Due to their bigger batteries, EVs tend to be significantly heavier than their internal combustion engine counterparts. Volkswagon‘s e-Golf, for example, is about 400 kilograms heavier than the gas-powered Golf VII. That added weight rests on the car’s tires, so EVs need tires that are sturdier.  EVs also tend to have more torque than combustion engines, which their tires need to be able to transfer to the road within seconds.  Leading tire manufacturers are working on improving tire designs, and innovating new chemical formulas to meet the needs of EVs. Some brands have introduced products specifically for use on battery-run vehicles, whereas others say they have adapted all of their tires to perform better for both EVs and combustion engine vehicles.  “We have been optimizing our product range for a long time, especially in terms of service life, rolling resistance and rolling noise — factors that are of particular benefit to electric vehicles,” a spokesperson for tire maker Continental told DW in a statement."
  },
  {
    id: 6,
    title: 'Why is climate denial still thriving online?',
    post_date: 'July 13 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/explained/explained-sci-tech/why-climate-denial-still-thriving-online-8828092/',
    thumb: 'https://images.indianexpress.com/2023/07/Social-media.jpg?w=640',
    description: 'A global heat wave has been blamed on climate change, yet online misinformation has evolved to counter the facts.',
    detail: "An extreme global heat wave has been blamed on climate change, yet online misinformation has evolved to counter the facts — despite platforms like TikTok banning climate denial.  Record global temperatures on July 3 kicked off the hottest week ever recorded as intense heat waves gripped the planet. Climate scientist Friederike Otto, of London’s Grantham Institute for Climate Change and the Environment, called the heat “a death sentence for people and ecosystems.”  Yet, the next day, a political journalist in the United Kingdom, Isabel Oakeshott, tweeted that “climate change headbangers panicking about a few hot days last month can calm down … It’s 13 degrees and pouring.” She added that she was “about to light the woodburner.” Within a day, over 2.2 million people had seen the tweet.  Oakeshott, a presenter on the conservative TalkTV news channel and former editor of the Sunday Times, often comments on Twitter about “climate change nuts.” On July 5, she asked: “Where’s Greta when it’s woolly jumpers in July?”  Amid the worst heat waves ever recorded in the United States, China, Mexico, Siberia and beyond, and near-unanimous scientific consensus that humans have induced global heating — in large part by burning fossil fuels — how does such denial continue to flourish?  The largest global survey on climate change opinion published in 2021 found that nearly 65% of people across diverse age ranges in more than 50 countries consider climate change a “global emergency,” yet researchers have found a recent resurgence in skepticism and denial."
  },
  {
    id: 7,
    title: 'Meta, Microsoft & Amazon join forces to challenge Google Maps dominance',
    post_date: 'July 27 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/technology/tech-news-technology/overture-challenges-google-maps-dominance-8861852/',
    thumb: 'https://images.indianexpress.com/2023/07/overture-map-data-featured.jpg?w=640',
    description: "Overture could mean a major shakeup for the online maps industry.",
    detail: "Online maps are essential for many mobile apps and emerging technologies — take food delivery apps like Swiggy, for instance — but they are mostly controlled by two tech giants: Google and Apple. These companies charge app developers for using their maps as a service and do not share the underlying data that powers them. However, a new initiative by Meta, Microsoft, Amazon Web Services, and TomTom aims to change that.  Formed late last year, the Overture Maps Foundation is a collaborative effort to create and maintain open and free base map data that anyone can use to build their own maps. The foundation has collected 59 million points of interest, such as restaurants, landmarks, streets and regional borders, and plans to update them regularly with the help of artificial intelligence and other techniques.  Marc Prioleau, executive director of the OMF, told CNBC in an interview that there are companies that “if they wanted to invest to build the map data, they could.” However, companies prefer if they “just get collaboration around the open base map” rather than spend that kind of money.  Since Google’s and Apple’s maps do not grant access to the data behind them, they do not suit many companies. These companies offer their maps as a service, often charging app makers for each map request via an API. Meanwhile, by using Overture’s more readily-available data, app developers can customise their maps with their own proprietary information, such as pickup locations for delivery services, and avoid paying fees to Google or Apple. The foundation is offering this underlying data alone, leaving it up to other companies to build apps on top.  Overture hopes to provide a more reliable and curated alternative to OpenStreetMap, a crowdsourced map project that Meta uses in its own maps. It also hopes its members can contribute enough real-time information to enable the regular release of accurate updates instead of a one-time data dump. To make this possible, Prioleau plans to use AI and other automated techniques."
  },
  {
    id: 8,
    title: 'Apple could be developing an iPhone with zero bezels',
    post_date: 'July 27 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/technology/tech-news-technology/apple-could-be-developing-an-iphone-with-zero-bezels-8861462/',
    thumb: 'https://images.indianexpress.com/2023/07/iphone-14-featured-1.jpg?w=640',
    description: "Apple is reportedly working on a new iPhone design that would completely eliminate the front bezel and offer a truly edge-to-edge display.",
    detail: "With the iPhone X, Apple offered an iPhone that was all-display at the front for the first time (minus the notch that is). Subsequent releases trimmed down on those bezels further but Apple could now be planning on doing away with those entirely.  According to a report by TheElec, Apple is working on a new iPhone design that would completely eliminate the front bezel and offer a truly edge-to-edge display. The company has asked its OLED screen suppliers, Samsung Display and LG Display, to develop a version of the display that has no bezels at all.  The report claims that Apple also wants the suppliers to improve the technologies for Thin Film Encapsulation (TFE) – which is the technology that enables stronger, lighter, and more flexible AMOLED – and under-panel camera (UPC).  Creating a flat bezel-less display is not easy, though, as it involves making the TFE thinner and overcoming the limitations of UPC. Thinning the TFE could compromise its ability to block moisture and oxygen.  Apple has a rather cautious approach to picking hardware for its iPhones. The company has reportedly rejected the curved edge display technology that Samsung and other vendors have used, as it causes optical distortion and increases the risk of breakage. Instead, Apple wants a flat display that covers the entire front of the iPhone."
  },
  {
    id: 9,
    title: 'Australia Court Fines Meta $14 Million for Undisclosed Data Collection Through Smartphone App',
    post_date: 'July 26 2023',
    genre: 'Technology',
    ref: '',
    thumb: 'https://images.news18.com/ibnlive/uploads/2023/03/gavel-16795687193x2.png?impolicy=website&width=219&height=147',
    description: "Australia's Federal Court also ordered Meta, through its subsidiaries Facebook Israel and the now-discontinued app, Onavo, to pay A$400,000 in legal costs to the Australian Competition and Consumer Commission, which brought the civil lawsuit.",
    detail: "An Australian court ordered Facebook owner Meta Platforms to pay fines totalling A$20 million ($14 million) for collecting user data through a smartphone application purporting to protect privacy without disclosing its actions. Australia's Federal Court also ordered Meta, through its subsidiaries Facebook Israel and the now-discontinued app, Onavo, to pay A$400,000 in legal costs to the Australian Competition and Consumer Commission, which brought the civil lawsuit. From early 2016 to late 2017, the company which was then called Facebook advertised Onavo as a way for people to keep their personal information safe but collected their location, time and frequency using other smartphone apps, and websites they visited for its own commercial purposes, the judge Wendy Abraham said in a written judgment on Wednesday. 'The failure to make sufficient disclosures … may have deprived tens of thousands of Australian consumers of the opportunity to make an informed choice about the collection and use of their data before downloading and/or using Onavo Protect', Abraham wrote. She added that the court could have fined Meta hundreds of billions of dollars since Australians downloaded the app 271,220 times and each breach of consumer law carried a A$1.1 million fine, but 'the contraventions can be characterised as a single course of conduct'. The fine was agreed by the regulator and Meta but 'carries with it a sufficient sting to ensure that the penalty amount is not such as to be regarded … as simply an acceptable cost of doing business', she wrote."
  },
  {
    id: 10,
    title: 'Apple Starts Accepting Requests For Vision Pro Headset Developer Kits: Eligibility And More',
    post_date: 'July 25 2023',
    genre: 'Technology',
    ref: '',
    thumb: 'https://images.news18.com/ibnlive/uploads/2023/06/apple-vision-pro-headset-16860211143x2.jpg?impolicy=website&width=219&height=147',
    description: "Apple made waves in the tech world when it revealed its mixed reality headset—the Vision Pro, which the iPhone maker calls a “spatial computer.” It is anticipated to be Apple's most significant launch since the Apple Watch in 2015. The iPhone maker has now started accepting applications for its Vision Pro developer kit, which will allow developers to create apps and experiences for the headset.",
    detail: "Apple made waves in the tech world when it revealed its mixed reality headset—the Vision Pro, which the iPhone maker calls a “spatial computer.” It is anticipated to be Apple's most significant launch since the Apple Watch in 2015. The iPhone maker has now started accepting applications for its Vision Pro developer kit, which will allow developers to create apps and experiences for the headset. Apple is now accepting applications from interested developers for a “loaner” Vision Pro developer kit, as reported by The Verge. 'We'll loan you a Vision Pro developer kit to prepare your app for the launch of the new App Store on Vision Pro,' Apple said. And along with the kit, developers will also can avail help setting up the device, guidance by Apple experts for UI design and development and two 'code-level support requests,' so that developers can troubleshoot their code.  Developers will also need to return their Vison Pro developer kits when Apple asks. As per Apple, the kits will let developers build, iterate, and test on Vision Pro. Apple has also listed a number of requirements that must be met in order to be eligible for a developer kit. First, you must be an Account Holder in the Apple Developer Program and second, provide information about your development team's skills and any existing apps. Apple also mentions that it will prioritize developers who are working on “creating an app that takes advantage of visionOS features and capabilities.” This means that any developer looking to create a native app from scratch will have an easier time being noticed by Apple. The Apple Vision Pro will be available to consumers next year, but the exact release date is not yet known. The headset will cost $3499 and will be available in the US only, with availability for more countries coming later in 2024."
  },
  {
    id: 11,
    title: "Oppenheimer movie review: Christopher Nolan & Cillian Murphy deliver a riveting story of the American genius",
    post_date: 'July 20 2023',
    genre: 'Hollywood',
    ref: 'https://www.firstpost.com/entertainment/oppenheimer-movie-review-christopher-nolan-cillian-murphy-deliver-a-riveting-story-of-the-american-genius-12889142.html',
    thumb: 'https://images.firstpost.com/wp-content/uploads/2023/07/Collage-Maker-20-Jul-2023-08-54-AM-406.jpg?impolicy=website&width=640&height=363',
    description: "Before Oppenheimer, Cillian Murphy and Christopher Nolan worked together in Batman Begins (2005), The Dark Knight (2008), Inception (2010), The Dark Knight Rises (2012), and Dunkirk (2017)",
    detail: "The cinematic genius Christopher Nolan is one of the best minds in showbiz when it comes to delivering riveting, epic and extraordinary movies; The Prestige, Memento, The Dark Knight trilogy, Interstellar, Inception, Dunkirk & Tenet are classic examples of that. Talking about his new offering Oppenheimer, it narrates the magnificent tragic story of the American theoretical physicist J. Robert Oppenheimer (who is known as the ‘father of the atomic bomb’). Honestly, Oppenheimer has all the elements, which you expect from a Nolan film. Right from a haunting BGM, impeccable camerawork, emotional drama and twists with the superb combination of cerebral stuff and gripping, however, it gives you the experience of a non-Nolan affair. While the noise around Nolan not using CGI for the bomb explosion has been the talk of the town, in reality, the highlight is the filmmaker’s superlative narrative of the lead character (Cillian Murphy) and his life-changing incidents, that too in multiple shades, right from black-and-white to colour to symbolise the time and era. The historical psychodrama has a mesmerising first half, which includes Oppenheimer’s encounter with Albert Einstein (Tom Conti) at Princeton, his marriage to alcoholic Kitty (Emily Blunt) and other key incidents. But the second half surpasses your expectations, where we see the testing of the Atomic bomb, the World War II situation, Hiroshima & Nagasaki’s bombing effects and Oppenheimer being accused of the threat and questioning his loyalty to the United States of America. While Christopher Nolan has been a master of making every nuance and detail a perfect frame, this outstanding screenplay and cinematic experience has gone to the next level due to the exemplary performances of the ensemble cast. Cillian Murphy and Robert Downey Jr. have easily delivered their career-best performances and are expected to be top contenders in the categories of Best Actor and Best Supporting Actor in all major award ceremonies. Matt Damon is charming, sharp and charismatic as General Leslie Groves. Emily Blunt impresses with her emotional yet layered portrayal of Katherine Oppenheimer. Despite being a 3-hour long film, Oppenheimer is a visual spectacle, which should be seen on the 70 mm screen, especially in the IMAX format."
  },
  {
    id: 12,
    title: 'Hollywood’s troubles become our troubles’: How the actors’ and writers’ strike is affecting life in Los Angeles',
    post_date: 'July 17 2023',
    genre: 'Hollywood',
    ref: 'https://www.firstpost.com/explainers/hollywoods-troubles-become-our-troubles-how-the-actors-and-writers-strike-is-affecting-life-in-los-angeles-12875002.html',
    thumb: 'https://images.firstpost.com/wp-content/uploads/2023/07/2023-07-14T172515Z_921456280_RC2432ARO8SD_RTRMADP_3_TELEVISION-ACTORS.jpg?impolicy=website&width=640&height=363',
    description: "The ceased productions are not just a threat to the flow of dollars to restaurants and retailers that cater to film crews, but also a blow to the region’s cultural heart. Entertainers sponsor schools, embark on second careers as politicians, and stump for state ballot initiatives",
    detail: "Los Angeles County has 88 cities. Ten million people. Two hundred-plus languages spoken.  And a nine-letter sign that, for much of the world, defines the entire region: HOLLYWOOD.  Loss Angeles has long been regarded as the global “company town” for show business, and as a rare actors’ strike upended the signature industry this week, the potential for cascading economic impacts across Southern California has emerged as a critical local issue. But economists disagree on just how extensively the simultaneous actors’ and writers’ strikes will be felt.  Even by the most generous estimates, Hollywood has never supported more than about five per cent of employment in a region where many more people work in trade, health care, government and even Southern California’s diminished manufacturing sector. Yet Hollywood pervades Los Angeles life in ways as big as a movie backdrop or as small as a street detour on some awards night.  The impact on Los Angeles economy  For many, the ceased productions and darkened premieres are not just a threat to the flow of dollars to restaurants and retailers that cater to film crews, but also a blow to the region’s cultural heart.  “To the extent that Hollywood defines America’s idea of where I live, Hollywood’s troubles become my troubles,” said DJ Waldie, a cultural historian in Southern California. “When Hollywood stops, a great many things stop here, and not just a few studios.”"
  },
  {
    id: 13,
    title: '5 Hollywood actors who couldn’t handle fame and went crazy',
    post_date: 'June 27 2023',
    genre: 'Hollywood',
    ref: 'https://www.firstpost.com/living/7-hollywood-actors-who-couldnt-handle-fame-and-went-crazy-12796172.html',
    thumb: 'https://images.firstpost.com/wp-content/uploads/2023/06/image-11-1.jpg?impolicy=website&width=640&height=363',
    description: "Not everyone is equipped to handle the pressures that come with fame. In some cases, the intense spotlight and constant scrutiny can take a toll on an individual's mental well-being",
    detail: "Being a Hollywood actor comes with immense fame and fortune, but not everyone is equipped to handle the pressures that come with it. In some cases, the intense spotlight and constant scrutiny can take a toll on an individual’s mental well-being. Here are seven Hollywood actors who found it difficult to cope with their celebrity status and unfortunately went crazy.  1. Charlie Sheen: Known for his roles in movies like Platoon and the hit TV series Two and a Half Men, Charlie Sheen’s fame took a dark turn. He battled drug addiction and displayed erratic behavior, making headlines for his public meltdowns and controversial statements. Sheen’s struggles eventually led to his departure from the show that brought him immense success.  2. Amanda Bynes: Amanda Bynes rose to fame as a child star in Nickelodeon shows like All That and The Amanda Show. However, as she transitioned into adulthood, Bynes faced numerous personal and legal issues. She struggled with mental health problems, including bipolar disorder and substance abuse. Bynes’ public breakdowns and erratic behavior alarmed her fans and the industry alike.  3. Lindsay Lohan: Lindsay Lohan gained fame through movies like Mean Girls and Freaky Friday. However, her rapid rise to stardom took a toll on her mental health. Lohan battled substance abuse issues, resulting in legal troubles and a decline in her career. Her struggles with addiction and unstable behavior overshadowed her once-promising talent.  4. Britney Spears: One of the biggest pop stars of the late ’90s and early 2000s, Britney Spears faced immense pressure and scrutiny from the media. As her personal life spiraled out of control, she experienced a highly publicized breakdown in 2007. Spears’ struggles with mental health led to a conservatorship that limited her autonomy for over a decade. Her case shed light on the darker side of fame and sparked discussions about celebrity mental health.  5. Joaquin Phoenix: Joaquin Phoenix is an immensely talented actor known for his intense performances. However, after the death of his brother, River Phoenix, he fell into a period of deep grief and struggled with substance abuse. Phoenix’s unconventional behavior, including his “retirement” from acting and bizarre public appearances, raised concerns about his mental well-being. Fortunately, he later made a successful comeback."
  },
  {
    id: 14,
    title: 'Priyanka Chopra’s Citadel 2: Is the $300 million budget show of the Russo Brothers not coming up with Season2?',
    post_date: 'May 26 2023',
    genre: 'Hollywood',
    ref: 'https://www.firstpost.com/entertainment/priyanka-chopras-citadel-2-why-300-million-budget-show-of-the-russo-brothers-lost-the-sequel-chances-explained-12645582.html',
    thumb: 'https://images.firstpost.com/wp-content/uploads/2023/04/citabook.jpg?impolicy=website&width=640&height=363',
    description: "Priyanka Chopra Jonas starrer Citadel will or will not come out with Season 2. Some reports say that they wont. But the speculation is still on.",
    detail: "Earlier there were news that Priyanka Chopra’s Citadel will be coming up with its Season 2.  But later according to reports published in Hello magazine it was written that that Citadel has not officially been greenlit for a season 2.  A report in Forbes, quotes the reason for the same. The report states that Citadel might have had a good viewership and it booked the top spot on Prime, but the reason was majorly a scarcity for Prime Originals which made Citadel trend on their list.  Makers are sure that the series would grab a lot of headlines due to Priyanka Chopra Jonas but it was all about her professional and personal life, rather than about the show which put a serious question on the future of the $300 million series. But the speculation is still on.  About Citadel: Priyanka Chopra and Richard Madden’s show Citadel revolves around an international secret organisation Citadel. Priyanka Chopra plays the role of Nadia Sinh with Richard Madden as Mason Kane who are spy agents. The story goes this way that some eight years ago Citadel fell and these agents had narrowly escaped with their lives and remained hidden until one day when they get back together for yet another mission.  Verdict for Citadel: Citadel started off well. Visually appealing and two very attractive leads of the show, that is the main plus point of Citadel. But everything said and done, Citadel though pleasing to the eye, but there is not much newness to it. I would call Citadel to be a an above average routine spy thriller. It may not be a best spy thriller with a woman lead. But for me what matters is Priyanka Chopra’s professional achievement and how she grows with each project that she takes up in Hollywood. The first three episodes were good. But towards the end the viewers lost interest because there was nothing gripping about the content."
  },
  {
    id: 15,
    title: 'How AI is taking centre stage in Hollywood strikes',
    post_date: 'July 24 2023',
    genre: 'Hollywood',
    ref: 'https://www.firstpost.com/explainers/how-artificial-intelligence-is-taking-centre-stage-in-hollywood-strikes-12905662.html',
    thumb: 'https://images.firstpost.com/wp-content/uploads/2023/07/AP23202735549919.jpg?impolicy=website&width=640&height=363',
    description: "As the technology to create without creators emerges, actors fear they will lose control of their lucrative likenesses. Unknown actors fear they'll be replaced altogether. Writers fear they'll have to share credit or lose credit to machines",
    detail: "Artificial Intelligence has sent shockwaves through creative sectors. The capacity to generate plausible, complex written content has made scriptwriters question if their abilities will one day be obsolete.  AI has also begun to demonstrate astounding powers in creating images and video, forcing people to imagine what if it completely replaces the need for real filmmaking?  Now, there is a fear from the coming torrent of AI tools that will mean just about anyone could recreate a person’s likeness and have them appear to engage in performances or acts without their consent.  With this, artificial intelligence has surged to the forefront of Hollywood’s labour fights. Standing alongside more traditional disputes over pay models, benefits and job protections, AI technology is the wild card in the contract breakdowns that have led actors and writer’s unions to go on strike  Also Read: Is Hollywood shutting down? Why actors joined writers on strike  The technology has pushed negotiations into unknown territory, and the language used can sound utopian or dystopian depending on the side of the table. Here’s a look at what the unions and their employers each say they want.  AI, the hot-button issue  As the technology to create without creators emerges, star actors fear they will lose control of their lucrative likenesses. Unknown actors fear they’ll be replaced altogether. Writers fear they’ll have to share credit or lose credit to machines.  The proposed contracts that led to both strikes last only three years. Even at the seeming breakneck pace at which AI is moving, it’s very unlikely there would be any widespread displacement of writers or actors in that time. But unions and employers know that ground given on an issue in one contract can be hard to reclaim in the next."
  },
  {
    id:16,
    title: 'Spyhide can steal your phone’s private data: Here’s how to find and remove it',
    post_date: 'July 26 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/technology/tech-news-technology/spyhide-can-steal-your-phones-private-data-heres-how-to-find-and-remove-it-8860964/',
    thumb: 'https://images.indianexpress.com/2023/07/Spyhide.jpg?w=640',
    description: "Spyhide's database contains 3.29 million text messages, 1,2 million call logs, 3,12,000 call recordings, 3,82,000 photos and 6,000 audio clips.",
    detail: "Spyhide is a stalkerware app that might be stealing your private and sensitive data like passwords, contacts, messages, call logs, and real-time location data among other things.  According to a report by TechCrunch, once installed on a device, the phone surveillance app automatically hides itself which makes it difficult to find and remove. When planted on a victim’s phone, it continuously uploads information from the device to a remote server in the background.  What did Spyhide steal?  While they often operate stealthily, stalkerware apps sometimes leak information stolen from the victim’s phone. In a blog post, a Switzerland-based hacker named Maia Arson Crimew said he was able to access Spyhide’s source code and got access to a web-based dashboard where the victim’s stolen phone information was displayed.  Crimew noted that Spyhide’s database had detailed records of somewhere around 60,000 affected Android devices, with some even dating back to July 2018. This included information about each file on the device like when a photo or video was taken, where it was taken and when it was uploaded.  The stolen data also includes 3.29 million text messages which have confidential information like two-factor authentication codes, password reset links and 1.2 million call logs with details like number of receiver, and length of call. In addition to this,  it also contained 3,12,000 call recordings, 9,25,000 contact details, records for 3,82,000 photos and around 6,000 audio clips that were silently recorded from the victim’s phone without their knowledge.  The report reveals that Spyhide was able to access devices across all continents. Brazil and Europe had thousands of victims, while the United States had approximately 3,100 victims. Although this may seem like a small number, they were the most monitored in terms of location data.  The database also stored information of more than 7,50,000 people who signed up to use Spyhide and wanted to install the stalkerware on someone’s phone. However, most people who signed up did not pay for the spyware or installed it on another device."
  },
  {
    id:17,
    title: 'AI lesson for Microsoft and Google: Spend money to make money',
    post_date: 'July 26 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/technology/artificial-intelligence/ai-lesson-for-microsoft-and-google-spend-money-to-make-money-8860479/',
    thumb: 'https://images.indianexpress.com/2023/07/AI-Reuters-1.jpg?w=640',
    description: "Microsoft said costs rose sharply as it built new data centers to support AI and that capital expenditures will continue to rise.",
    detail: "Artificial intelligence is expected to pay off big for tech giants including Microsoft and Alphabet someday. But expect deeper investments before gains trickle to the bottom line, the companies said on Tuesday.  Microsoft said costs rose sharply as it built new data centers to support AI and that capital expenditures will continue to rise as it buys chips from the likes of Nvidia Corp to power those data centers.  Microsoft is bearing AI costs in two ways, analysts said: to power its own products such as its forthcoming $30-a-month Copilot AI assistant, and to serve companies wanting to use its Azure cloud computing services to create AI products.  Microsoft executives said the service will start generating the bulk of its revenue in the second half of its fiscal 2024 ending June 30.  “They’re buying a bunch of H100s,” said Ben Bajarin, chief executive and principal analyst of Creative Strategies, referring to Nvidia’s flagship chips for AI.  “You’re probably going to see a similar thing with Amazon if not this quarter then the next quarter, because both of them are the clouds that the vast majority of the market is using for training (AI systems) right now.”  Alphabet, however, kept down costs, though not for long. Chief Financial Officer Ruth Porat, who will become president and chief investment officer, said delays in data center construction are why second-quarter capex was lower than expected.  “As far as AI is concerned, while Google may have spent upwards of $200 billion on AI investments over the past decade, much of that isn’t necessarily appreciated by users and investors,” said Scott Kessler, global sector lead for technology media and telecommunications at Third Bridge.  One advantage Google has, analysts said, is that it has its own custom chip for handling AI work called the Tensor Processor Unit (TPU), which helps lower costs.  Microsoft may be “aggressively buying Nvidia chips, given Microsoft does not have its own silicon as an alternative,” said Atlantic Equities analyst James Cordwell.  But Google conceded that it will buy chips from other companies as well as using its own, and Porat said that spending could put a drag on profit and growth."
  },
  {
    id:18,
    title: 'ChatGPT Android app now available in India, Bangladesh, US & Brazil',
    post_date: 'July 26',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/technology/artificial-intelligence/chatgpt-android-app-now-available-in-india-bangladesh-us-brazil-8860079/',
    thumb: 'https://images.indianexpress.com/2023/07/chat-gpt.jpg?w=640',
    description: "The Android version of the app is available on Play Store in four countries.",
    detail: "After months of anticipation, the ChatGPT mobile application is finally available for Android users. The Android app comes nearly two months after the iOS version was launched.  The app is now available in the US, India, Bangladesh, and Brazil. OpenAI has opted for a staged rollout instead of making the app available all at once worldwide.  The Sam Altman-led company had last week announced that users could expect the Android version of its sensational chatbot in the last week of July. Interestingly, the Android App comes at a time when ChatGPT has been grappling with reports of a slump in traffic and slower response times.  OpenAI has plans to expand the availability of the Android app in the coming weeks. While earlier the app was only restricted to iOS users, with the latest development, millions of Android users will be able to take advantage of ChatGPT. The app is free and syncs user history across devices, bringing the latest improvements from OpenAI.  ChatGPT, launched in November 2022 by OpenAI, is a large language model-based chatbot that has impressed the world with its astounding ability to offer human-like responses. The widespread adoption of the chatbot made it the fastest internet application to acquire as many as 100 million users in the shortest time – four months since its launch. It is built on GPT-3.5 and GPT-4. As of now, GPT-4 is only accessible to ChatGPT Plus members who have to pay Rs 1,999 as a monthly subscription in India."
  },
  {
    id:19,
    title: 'Elon Musk explains the reason behind Twitter’s rebranding as X',
    post_date: 'July 27 2023',
    genre: 'Technology',
    ref: 'https://indianexpress.com/article/technology/tech-news-technology/elon-musk-twitter-x-rebranding-explanation-8859858/',
    thumb: 'https://images.indianexpress.com/2023/07/Twitter-X-logo-explanation-20230725.jpg?w=640',
    description: "In a recent interview, Elon Musk revealed the real reason why he ditched the blue bird logo of Twitter.",
    detail: "Ever since Elon Musk announced the new logo for Twitter speculations are rife about the reasons behind the Chief Twit’s actions. On Monday, Musk unveiled a new logo, X, for Twitter purging the iconic blue bird logo that has cast a lasting imprint on the collective psyche of billions of users.  The new logo is a white X against the backdrop of pitch black and has already started to reflect on the web and mobile versions of the popular microblogging website.  While Musk has kept the world guessing about the true meaning of the sudden overhaul, a new report seems to be hinting at his grander intentions. A report on CNBC now claims that the name X represents Musk’s ambitions to create an all-encompassing platform ‘everything app’.  The 52-year-old technocrat said that the name Twitter made sense when it was just 140 characters going back and forth like birds tweeting. However, according to him now users can post ‘almost anything’.  Musk’s comments come at a time when the move is being perceived as risky by analysts as it is reverting decades of branding that went into making the brand Twitter.  Elon Musk took over Twitter in October 2022 after a prolonged acquisition drama. Ever since the acquisition, the Tesla boss has made several sweeping changes such as staff reduction and introducing a subscription model where anyone could get the coveted verified badge. He had even momentarily changed the logo to that of a dog named Shiba Inu after taking over the platform.  His most recent change was deploying former NBCUniversal executive Linda Yaccarino as CEO of Twitter. She took over the reigns as the new CEO on June 5, and the rebranding is the biggest development after her induction.  On Monday, Yaccarino was among the executives who confirmed the rebranding. She took to her Twitter account to post “X is here! Let’s do this.” The CEO also posted a picture of the logo projected on the company’s offices in San Francisco."
  },
  {
    id:20,
    title: 'The Kardashians Season 3 Episode 10: Release Date, Air time, Plot and More',
    post_date: 'July 26 2023',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/hollywood/the-kardashians-season-3-episode-10-release-date-air-time-plot-and-more-101690392098175.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/26/550x309/2b7a8-16903738655020-1920_1690393802885_1690393828010.webp',
    description: "The exciting season finale of The Kardashians Season 3, Episode 10, will be available worldwide on Thursday, July 27th. Here's everytghing you need to know.",
    detail: "The Kardashians are returning with a new episode this week, and it will be the last episode of season 3.They will all come together as a family to wrap up the season.In this episode, there will be a sad moment as they find out that Tristan Thompson's mother has passed away. Kris, Kim, and Khloe will travel to Toronto to attend the funeral and support Tristan. Besides that, Kylie will talk about changing her son's name legally, and Kourtney will share her experience of dealing with criticism for her collaboration with Boohoo.  The exciting season finale of The Kardashians Season 3, Episode 10, will be available worldwide on Thursday, July 27th, 2023.  Where to Watch The Kardashians Season 3?  In the US, you can watch The Kardashians on Hulu, while in the UK, the show will premiere on Disney+.  What to expect from the upcoming episode of The Kardashians season 3?  In the exciting new episode of The Kardashians season 3 (episode 10), the family receives some really sad news about Tristan's mom, Andrea Thompson. She suddenly passed away after having a heart attack. Kim describes it as a tough week and says it's a super shocking way to begin the new year.  The Kardashians’ Kris Jenneris crying while imagining how Khloe's baby's father must be feeling.  “All of a sudden, you’re stripped of the caretaker that you had your whole life.”  In the clip, Khloe Kardashian shares that Tristan was crying on the phone,while trying to tell her that she was gone."
  },
  {
    id:21,
    title: "Ram Gopal Varma on Oppenheimer's Bhagavad Gita controversy: ‘The irony is…’",
    post_date: 'July 24 2023',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/hollywood/ram-gopal-varma-oppenheimer-bhagavad-gita-controversy-the-irony-101690202550599.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/24/550x309/oppenheimer_rgv_1690202909213_1690204197742.jpg',
    description: "Ram Gopal Varma, who has been heaping praises on Christopher Nolan's Oppenheimer, also opined on the Bhagavad Gita controversy surrounding the film.",
    detail: "Ram Gopal Varma has been immensely generous towards Christopher Nolan's new film Oppenheimer in his series of tweets from Sunday. However, it was only a matter of time before the outspoken filmmaker tweeted his take on the film's Bhagavad Gita controversy. (Also Read: Twitter thinks 'best ever CGI award goes to censor board' for Florence Pugh's black dress in Oppenheimer sex scene)  On Monday, Ram Gopal Varma tweeted, 'Irony is that an American nuclear scientist Oppenheimer read the Bhagwad Geeta which I doubt even 0.0000001 % of Indians read.'  His tweet is in reference to a contentious scene in the film, where the protagonist J. Robert Oppenheimer (played by Cillian Murphy), known as ‘the father of the atomic bomb,’ is seen invoking a verse from the holy Hindu scripture Bhagavad Gita immediately after a lovemaking scene with his girlfriend (played by Florence Pugh).  A user seemed to agree with Ram Gopal Varma's remark and wrote in the comment section of his tweet, “That too in Sanskrit, after learning Sanskrit.” Another user wrote, “We’ve heard enough Bhagavath Geetha interpretations from others than reading it once with our own interpretation unbiased and unprejudiced.”  A user also reacted to the objections raised by a section of the internet over how the scene plays out. They wrote, “Indians are more worried about showing the bhagvad gita in a bedroom.”  However, another user countered Ram Gopal Varma's remark and wrote, “Many Indians have read the Bible which I doubt 0.000000001% of Americans have ever dared to read...doesn't mean a thing RGV...” Another user wrote, “Bigger irony is that it includes you too sir!” Another user argued, “How can majority hindus understand it as it was in coded language, as it was the prerogative of a particular class to know the language for hundred of years.”"
  },
  {
    id: 22,
    title: 'Doctor Strange in the Multiverse of Madness overtakes The Batman to become highest-grossing film of 2022',
    post_date: 'May 29',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/hollywood/doctor-strange-in-the-multiverse-of-madness-overtakes-the-batman-to-become-highest-grossing-film-of-2022-101653814691150.html',
    thumb: 'https://images.hindustantimes.com/img/2022/05/29/550x309/BO_1653817255495_1653817275340.jpeg',
    description: "Marvel's Doctor Strange in the Multiverse of Madness is now the highest-grossing film of 2022 globally, having overtaken DC's The Batman.",
    detail: "Marvel’s latest theatrical release Doctor Strange in the Multiverse of Madness has added another feather to its hat. The Benedict Cumberbatch and Elizabeth Olsen-starrer has overtaken rival stable DC’s The Batman as the highest-grossing film of the year. As of Saturday, the Marvel film had earned over $800 million globally. The Batman, which released in March, has lifetime earnings are $769 million. Also read: Doctor Strange in the Multiverse of Madness: Charlize Theron introduces her character Clea, fans welcome her to the MCU  According to a Forbes report, Doctor Strange in the Multiverse of Madness has now earned over $350 million in the US and an additional $465 million overseas, giving it a global gross of $815 million approximately. Trade experts predict the film to complete $950 million globally but are uncertain if it will reach the billion-dollar mark.  Doctor Strange in the Multiverse of Madness is part of the expansive Marvel Cinematic Universe and is the direct sequel to the 2018 film Doctor Strange. It also continues the storylines of Marvel and Sony’s Spider-Man: No Way Home and the Disney+ series WandaVision. Trade experts say this interconnectivity helped the film as people flocked to watch ‘the latest Marvel film’. The film is directed by Sam Raimi.  The Batman, on the other hand, is a stand-alone film with no connection to the DC Extended Universe, which includes tentpoles like Justice League, Aquaman, and Wonder Woman. The Batman failed to replicate the success of DC’s other hits like Aquaman and The Dark Knight (another Batman film), both of which made over $1 billion at the global box office.  Trade insiders have chalked it partly to the pandemic and partly to the film’s dark, noir tone. Robert Pattinson made his debut as Batman in the Matt Reeves film, which also starred Paul Dano, Zoe Kravitz, Colin Farrell, and Jeffrey Wright. A sequel has been announced.  Get more updates from Bollywood, Hollywood, Musicand Web Seriesalong with Latest Entertainment Newsat Hindustan Times."
  },
  {
    id: 23,
    title: 'Top Gun Maverick box office day 1 collection: Tom Cruise film opens to $51 million in US, collects ₹4.75 crore in India',
    post_date: 'May 28 2023',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/hollywood/top-gun-maverick-box-office-day-1-collection-tom-cruise-film-opens-to-51-million-in-us-collects-4-75-crore-in-india-101653747498962.html',
    thumb: 'https://images.hindustantimes.com/img/2022/05/28/550x309/dcf35a88-dd9e-11ec-8fe2-ac5ac3115257_1653667000472_1653747840857.jpg',
    description: "Top Gun Maverick box office day 1 collection: Tom Cruise's film collected $51 million at the US box office on its opening day. In India, it collected ₹4.75 crore.",
    detail: "Director Joseph Kosinski's Top Gun Maverick, which features Tom Cruise, had a contrasting opening at the box office in India and the US. In the US, the film collected $51 million on its opening day. The film is already Tom’s best opening day ever beating Mission Impossible – Fallout's first-day collection. However, the film has not been able to make a mark in India and collected ₹4.75 crore on day one.  In Top Gun Maverick, Tom essays the role of Pete 'Maverick' Mitchell, who is grappling with the diminished standing of fighter pilots in a world that now wages war with drones controlled by people miles away on computers. Top Gun Maverick is produced by Jerry Bruckheimer, Tom Cruise, Christopher McQuarrie and David Ellison.  As per a Deadline report, 'Top Gun Maverick at this Friday night hour is on its way to a $51 million opening day (which includes $19.3 million previews). It would not be shocking to wake up on Saturday morning and see that the sequel has edged out Iron Man 2 ($51.2M) to become Paramount’s top opening day ever. Already, the sequel is Tom Cruise’s best opening day ever in US/Canada besting Mission: Impossible – Fallout‘s first day of $22.8M by 124%.'  According to Boxofficeindia.com, 'Top Gun Maverick has also not been able to make much of an impact in India as collections have been poor over the first two days though it should do better than Anek. The film is doing outstanding business in North America and may well go close to $150 million over the four day holiday weekend. The collections of Top Gun Maverick in India are as follows: Wednesday - ₹25,00,000, Thursday - 2,00,00,000, Friday - 2,50,00,000. Total - 4,75,00,000 approx.'  The Hindustan Times review read, 'The sequel is not a superior film but it accomplishes a far tougher task--tie in the loose ends and culminate a story arc that began almost four decades ago. If Top Gun was a coming-of-age film, Maverick is about redemption and comebacks. It puts Maverick at a cross road in his life and career, where he knows he is running out of time but does not know how to let go. Tom Cruise has brought out the stubbornness and charm of the character wonderfully. And he has also allowed Maverick to grow older and somewhat wiser over the years. Despite the larger-than-life setting, he seems relatable, and the audience will grow to love him easily.'"
  },
  {
    id: 24,
    title: 'Johnny Depp thanks cops, photographers while leaving courthouse as trial nears end: ‘See you down the road’. Watch',
    post_date: 'May 28 2023',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/hollywood/johnny-depp-thanks-cops-photographers-while-leaving-courthouse-as-trial-nears-end-see-you-down-the-road-watch-101653725554761.html',
    thumb: 'https://images.hindustantimes.com/img/2022/05/28/550x309/US-CLOSING-ARGUMENTS-BEGIN-IN-DEPP-V--HEARD-TRIAL-5_1653726305859_1653726337385.jpg',
    description: "On Friday, Johnny Depp thanked police officers and photographers stationed outside the Virginia courthouse, where he is fighting a defamation suit against ex-wife Amber Heard.",
    detail: "The trial for the defamation suit filed by Johnny Depp against his ex-wife Amber Heard is nearing its end. On Friday, the judge handed over the case to the jury for deliberation after lawyers for both parties presented their closing arguments. On Saturday, a video emerged showing Johnny walking out of the courthouse with a smile on his face, greeting and shaking hands with everyone present there, from police officers to the paparazzi. Also read: Aly Goni shares video of fans cheering for Johnny Depp outside courtroom, says he'd be 'trolled to death' in India.  Given the case’s high profile nature, there is a lot of public interest in it. Every day, fans throng the courthouse in Virginia where the trial is underway. There have been several videos of fans cheering for Johnny over the weeks. On Saturday, Law & Crime Network shared one such video where Amber and Johnny were seen leaving the courthouse after Friday’s hearing. In the video, when Johnny exits the courthouse, a loud cheer goes up among the waiting fans. The actor is seen shaking the hands of all security personnel present and thanking them. He takes something out of his pocket and shows it to them with a smile.  The actor then turns towards the cameraman, recording it, and shakes his hand as well, before saying, “See you down the road!” Giving a salute to the camera, he then gets inside the car and waves to the fans before driving away.  Johnny has sued Amber for $50 million saying she defamed him when she claimed to be a victim of domestic violence in a Washington Post op-ed in 2018. Johnny’s lawyers have said that even though Amber didn’t name him, the implication damaged his career. He has further alleged that Amber was abusive towards him during their marriage.  Amber has countersued him for $100 million claiming that he has smeared her name by calling her a liar. She has maintained that she suffered physical and sexual abuse at Johnny’s hands.  Both trials have been running concurrently in Virginia for over a month. The jury is currently in deliberation and a verdict is expected to be delivered by the end of this month or in the first week of June."
  },
  {
    id: 25,
    title: "Spoiler alert: Amber Heard's witness blurts out major plot details of Aquaman and the Lost Kingdom",
    post_date: 'May 25 2023',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/hollywood/spoiler-alert-amber-heard-s-witness-blurts-out-major-plot-details-of-aquaman-and-the-lost-kingdom-101653383100722.html',
    thumb: 'https://images.hindustantimes.com/img/2022/05/24/550x309/aquaman_2_1653384797398_1653384803502.jpg',
    description: "Giving her testimony in Amber Heard's defence, entertainment expert Kathryn Arnold blurted out too many details about the actor's role in Aquaman and the Lost Kingdom.",
    detail: "As one of Amber Heard's witnesses presented her testimony in court to highlight how Johnny Depp's attorney Adam Waldman's statements severely hurt her film career, she accidentaly revealed some of her upcoming movie Aquaman and the Lost Kingdom's major spoilers. She blurted out a lot about Amber's part in the film. Also read: Johnny Depp laughs in courtroom at psychiatrist's weird replies about Marlon Brando: 'Isn't he dead?'  According to Entertainment Weekly, entertainment expert Kathryn Arnold said, 'I believe that in the first act of the movie, she was injured somehow, or it had something to do with a baby.' This allowed Aquaman fans to join the dots as Aquaman and Queen Mera did get married and have a child in the comics.  She claimed not reading the script and said that she only knew how much Amber told her about the script. She said Mera 'ends up in the hospital early in this new Aquaman 2 movie and doesn't really come out until the end to kind of wrap things up.' She said Amber's Mera's interactions with Jason Momoa's Aquaman and the action scenes were taken out from the film. Kathryn talked about how Amber had trained very hard for several months for an action sequence but when she arrived on the set, her role had shrunk and the scene was chopped out.  Kathryn also said Johnny's habitual 'tardiness, drinking and drug abuse' had hurt his career along with pursuing this and other lawsuits. 'He's causing his own demise,' she said."
  },
  {
    id: 26,
    title: "Sunny Deol blames 'hatred between India and Pakistan' on political games at Gadar 2 trailer launch, gets slammed",
    post_date: 'July 27 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/bollywood/sunny-deol-gadar-2-trailer-hatred-between-india-and-pakistan-political-games-101690429294083.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/27/550x309/gadar_2_trailer_1690429577278_1690429610871.jpeg',
    description: "After Sunny Deol said 'political blame game' was responsible for 'hatred between India and Pakistan', a section of social media users criticised his statement.",
    detail: "The cast and makers of Gadar 2 unveiled the trailer for Gadar 2, the sequel to Anil Sharma's 2001 blockbuster cross-border drama, on Wednesday. At the Gadar 2 trailer launch event, which was held on the occasion of Kargil Vijay Divas, Anil was joined by actors Sunny Deol and Ameesha Patel, as well as the rest of Gadar 2 cast. Sunny's statement on India-Pakistan relations at the trailer launch of his upcoming movie attracted attention, with many on Twitter, now termed X, criticising the actor.  The actor and BJP MP from Punjab’s Gurdaspur blamed the 'political game' for the hatred between India and Pakistan. Many on social media were unhappy with his 'diplomatic' statement, with some claiming he made the remark so people in Pakistan would watch Gadar 2. Others said the film should be boycotted because of Sunny's statement.  At Gadar 2 trailer launch, Sunny Deol said, 'Kuch le jane ya lene-dene ki baat nahi hoti hai. Baat hoti hai insaniyat ki. Jhagde nahi hone chahiye. Dono taraf utna hi pyar hai, yeh siyasi khel hota hai jo sab nafratein paida karta hai. Aur woh hi aap dekhenge iss film mein bhi. Janta nahi koi chahti ki ek dusre ke sath hum jhagda kare. Aakhir hai toh sab iss hi mitti se (The essence lies in humanity, not in taking or giving. A conflict between the two sides should not prevail. There is love on both sides. It is the political blame game that creates hatred between India and Pakistan, a theme reflected in this film. Both nations comprise of people who seek peace, as we are essentially one and the same).'  A person said on X, 'Come out of your cave, Sunny Deol. Go and visit Pakistani.' Another one said, 'It seems they want to run this film in Pakistan!! It means it will be super flop in India…' One person said, 'Gadar's USP was Pakistan bashing. The only plausible way for the Gadar sequel to succeed was to persist with that bashing, and make audience feel the nostalgia. But ironically the leading man is peddling the long dead 'aman ki asha (hope for peace)' sentiments at the promotions!'  A person also said, 'Is dialogue ke saath hi picture flop ho gai (With his statement, the film is already a flop). Boycott Gadar 2!' A person joked, 'This movie has such low buzz that even giving a boycott call will be considered as helping it. So let is die unsung unhonoured and unseen.'"
  },
  {
    id: 27,
    title: "Raghav Chadha on how his life changed after engagement with Parineeti Chopra: ‘My colleagues tease me a little less now'",
    post_date: 'July 27 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/bollywood/raghav-chadha-on-how-his-life-changed-after-engagement-with-parineeti-chopra-101690426652285.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/27/550x309/parineeti_1683992129201_1690427001609.jpg',
    description: "Raghav Chadha revealed his life has changed after he got engaged to Parineeti Chopra on May 13. The AAP leader and actor are set to marry this year.",
    detail: "Parineeti Chopra and Raghav Chadha got engaged in May in New Delhi and the actor and Aam Aam Aadmi Party (AAP) leader will reportedly marry later in 2023. In a new interview with The Quint, Raghav Chadha opened up about life after engagement with Parineeti Chopra. The politician said that his colleagues and seniors tease him less now, since he is set to marry soon.  The two never publicly spoke about them dating, but reportedly, they knew each other for several years before making their relationship official in May. Since their engagement, pictures and videos of them from Rajasthan had surfaced online as they visited various locations, scouting for their wedding venue.  Recently Raghav was asked how his life had changed after engagement with Parineeti. 'Well, I think we should restrict this conversation to political alliances and not personal alliances. But yes, most certainly, my colleagues, co-workers in the party, and my seniors tease me a little less now... Earlier they used to ask me to get married, now they tease me a little less because they know I am getting married soon,' Raghav told The Quint.  Parineeti Chopra and Raghav Chadha got engaged in the presence of family and friends on May 13 at Kapurthala House in New Delhi. The couple was twinning in white ethnic outfits for the ceremony that was attended by everyone from actor Priyanka Chopra to Delhi chief minister Arvind Kejriwal. After their engagement, Parineeti and Raghav had also stepped out to greet the paparazzi and posed for photos as they made their first public appearance as a newly-engaged couple.  As per a recent Hindustan Times report, Parineeti and Raghav are looking for their wedding venue, and are planning to get married between September and November this year in Rajasthan. According to a source, Parineeti went scouting for the venue in Udaipur and is also exploring Kishangarh. While she went solo to Udaipur, she was joined by Raghav for the rest of the tour in Rajasthan."
  },
  {
    id: 28,
    title: "Rocky Aur Rani Kii Prem Kahaani box office prediction: Alia Bhatt-Ranveer Singh could open to ₹8-10 cr haul",
    post_date: 'July 27 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/bollywood/rocky-aur-rani-kii-prem-kahaani-box-office-prediction-101690374145054.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/26/550x309/Ranveer_Singh_Alia_Bhatt_1688177433634_1690377050952.jpg',
    description: "Trade experts believe that Rocky Aur Rani Kii Prem Kahaani is likely to make an opening weekend collection of ₹35-40 crore.",
    detail: "Given the buzz around Karan Johar's latest directorial venture, trade experts believe Rocky Aur Rani Ki Prem Kahaani will likely make an opening collection of ₹8-10 crore on Friday. The film stars Alia Bhatt, Ranveer Singh, Dharmendra, Shabana Azmi, and Jaya Bachchan in the lead roles. It is slated for a theatrical release on July 28  Producer and film business expert Girish Johar said that he expects a good opening for Rocky Aur Rani Ki Prem Kahaani. “It is the one big film after Pathaan. We have had Zara Hatke Zara Bachke and Satyaprem Ki Katha (that performed well at the box office) this year, but these were mid-budget films.”  He added that the film may open at anything between ₹8-10 crore on Friday, and the collections will hopefully rise over the weekend. 'If the audience really loves the film, and it manages a double-digit score on day one…if it maintains that, and rises to ₹12 crore or so on the second and third days, it can comfortably make ₹35-40 crore in the first weekend. Anything above that would be excellent, but anything below would mean that the film failed to match the audience's expectations. But that remains to be seen.'  “Now this one not only comes from Dharma - a premium production company of the country - but also boasts of top A-listers from the industry. We have veterans like Jaya ji, Dharmendra ji, and Shabana ji. We also have the cream from the current lot - Ranveer and Alia,” Girish said, adding that the film's director (Karan) also adds to the credibility."
  },
  {
    id: 29,
    title: 'Kareena Kapoor shares sweet picture of Jeh taking a nap with her from vacation',
    post_date: 'July 26 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/bollywood/kareena-kapoor-shares-sweet-picture-of-jeh-taking-a-nap-with-her-from-vacation-101690379532313.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/26/550x309/kareena_1690380467475_1690380467799.jpg',
    description: "Kareena Kapoor took to Instagram to share an adorable snap with Jeh from her holiday. She was seen taking a nap with Jeh.",
    detail: "A new picture from Kareena Kapoor's vacation with her family has surfaced online. The family is enjoying a long holiday in Europe. Kareena took to Instagram on Wednesday and shared a sweet picture that featured Jeh. Both of them were seen taking an afternoon nap in a garden.  The picture showed Kareena taking a nap on the field, with a blue bedsheet spread on the ground. Jeh was seen leaning on her back and resting his head near her shoulder. None of their faces were visible in the picture. Kareena added a sweet caption with the picture and wrote, 'That mood when you know your Summer holiday is coming to an end in few days…(red heart and laughing face emoticons)' She added the hashtags 'The Nap Life' and 'Mother son naps' in the caption too.  Kareena has been sharing several photos from the holiday with her family. Earlier, she had shared a photo featuring Saif, Taimur Ali Khan and Jehangir near a net in a garden as they seemingly played. The picture, which was clicked from afar, showed Saif, Taimur and Jehangir Ali Khan with their backs towards the camera and looking in the same direction.  Previously, she had also shared a picture of herself sitting and observing Saif and the kids from a distance as they held a fish, which they seemingly caught. The next one featured Saif with Taimur as both held fishing rods by a lake. While it's not known which part of Europe they are currently in, previously they were in Italy.  Kareena and Saif got married on October 2012 in Mumbai, after years of dating. They were blessed with Taimur in 2016 and had Jeh in 2021.  Upcoming projects  Fans will see Kareena in director Sujoy Ghosh's thriller which is based on the book The Devotion of Suspect X. It also stars Vijay Varma and Jaideep Ahlawat. Apart from that, she also has director Hansal Mehta's next untitled film in the pipeline.  Kareena also has The Crew in the pipeline alongside Tabu, Kriti Sanon and Diljit Dosanjh in the lead roles. It is a story of three women and is touted as a laugh riot, set against the backdrop of the struggling airline industry. Kapil Sharma will also be seen in a special cameo role in The Crew which is all set to hit the theatres on March 22, 2024."
  },
  {
    id: 30,
    title: 'Vivek Agnihotri slams Adipurush, says people will not accept just anyone as God: ‘You are drinking every night...’',
    post_date: 'July 26 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/bollywood/vivek-agnihotri-slams-adipurush-makers-takes-dig-at-casting-101690359791225.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/26/550x309/Vivek_Agnihotri_Adipurush_1687933486323_1690360154806.jpg',
    description: "Filmmaker Vivek Agnihotri has reacted strongly to Om Raut-directed Adipurush, and said that audiences are not idiots that they would accept anyone as God.",
    detail: "Filmmaker Vivek Agnihotri has reacted to the Adipurush controversy. In an interview with The Times of India, Vivek said what he thought went wrong with the Om Raut film that released in theatres on June 16. Adipurush starred Prabhas, Kriti Sanon and Saif Ali Khan in pivotal roles.  Adipurush, which is an adaptation of the epic Ramayana, has drawn heavy criticism post-release. From critics to audiences, many voiced misgivings over certain dialogues in the film. Among the dialogues over which the makers have drawn flak are 'marega bete', 'bua ka bagicha hain kya' and 'jalegi tere baap ki'. In the face of online outrage and negative reviews, the makers of Om Raut's Adipurush revised the dialogues as well. All India Cine Workers Association also wrote a letter to Union Home Minister Amit Shah and Mumbai Police, demanding the registration of a case against the producer, director, and writer of the film.  In a new interview with The Times of India, Vivek said, 'When you make something you don't believe in, just because aajkal ye chal raha hai (today this topic is trending), you are definitely going to go wrong. When you pick up stories of faith, either you yourself should have 100% conviction or you should be well versed in the subject like a historian, but unfortunately no one does that in India... Anybody who will try to take stars for either Mahabharata or Ramayana, will never be able to complete it… There's a reason why Mahabharat, Bhagavad Gita and Ramayana have been entrenched in everyone's psyche for years. If something has lasted for 5000 years, there has to be a reason for it.'"
  },
  {
    id: 31,
    title: "Uorfi Javed shares video of men who ‘harassed’ her on flight, says she's not ‘public property’",
    post_date: 'July 22 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/web-series/uorfi-javed-shares-video-of-men-who-harassed-her-on-flight-101690011363631.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/22/550x309/uorfi_javed_1690011358214_1690011358501.jpg',
    description: "Uorfi Javed is upset after a bunch of men allegedly harassed her on a flight from Mumbai to Goa. She posted their video on Instagram.",
    detail: "Reality show star Uorfi Javed had a bad experience on a recent flight from Mumbai to Goa. The actor has written in a new note on Instagram that she was harassed by a bunch of men on the flight who said ‘nasty things’ to her.  Sharing a video that was shot inside an Indigo flight, Uorfi showed the men who allegedly misbehaved with her. A few were sitting next to her and in front of her while others stood up from their seats. All of them were laughing. However, she had muted the video. Sharing it on her IG stories, Uorfi wrote with the video, 'While travelling from Mumbai to Goa on one of the flights yesterday I had to go through harassment, the men in this video were saying nasty things, Eve teasing and calling names. When I confronted them one of them said that their friends were drunk. Being drunk is no excuse to misbehave with women. Public figure YES, Public property NO.'  Uorfi gained limelight after appearing on Bigg Boss and Splitsvilla. She is known for her quirky, risque DIY fashion choices and appearances.  Recently, in an interview to Humans of Bombay, Uorfi spoke about how her pictures once landed on a porn site when she was still a teenager. 'When I was 15, someone uploaded my picture on a porn site. It was a normal picture. I uploaded it wearing a tube top as my Facebook profile photo. Someone downloaded them and uploaded it on a porn site without morphing, without anything. Slowly, everyone got to know about it. Everyone started blaming me a lot. I was told I am a porn star. I was like ‘Where is the video?’ But they said, ‘No, no she is a porn star’,' she said."
  },
  {
    id: 32,
    title: 'Karan Johar to turn Student of the Year movie franchise into a web series starring Shanaya Kapoor: Report',
    post_date: 'July 20 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/web-series/student-of-the-year-3-karan-johar-to-launch-shanaya-kapoor-web-series-101689825080831.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/20/550x309/shanaya_kapoor_Karan_Johar_1689825603118_1689825616554.jpg',
    description: "Karan Johar will launch Shanaya Kapoor in the OTT space with Student of the Year 3, as per a new report; the web series will stream on Disney+ Hotstar",
    detail: "Karan Johar is turning his Student of the Year movie franchise into a web series, as per a new report. The next installment, Student of the Year 3 (SOTY 3), will also mark the OTT debut of budding actor Shanaya Kapoor, Sanjay Kapoor and Maheep Kapoor’s daughter.  It was recently announced that Shanaya Kapoor's film debut will not be Karan's Bedhadak; she'll be launched with Mohanlal's pan-India film Vrushabha instead. Shanaya has already worked in the capacity of an assistant director on cousin-actor Janhvi Kapoor-starrer Gunjan Saxena: The Kargil Girl. However, her transition into acting has been discussed over the past few years.  Karan Johar is turning the Student of the Year movie franchise into a web series in partnership with Disney+ Hotstar, as per a Pinkvilla report. The project is currently in the writing stage and is scheduled to go on floors in the last quarter of this year, added the report. The Disney+ Hotstar show is expected to introduce some more fresh faces alongside Shanaya, and the casting process for that is reportedly underway.  Further details about the show's plot are awaited, but as per the sources quoted in the report, the work on this series is going on in full swing at Dharma’s digital content arm, Dharmatic Entertainment. The director for the series is expected to be finalised within a month.  News of Shanaya's Bollywood launch has been around for the past two years. The star kid was initially set to make her acting debut with Karan Johar's Bedhadak, alongside Lakshya Lalwani and Gurfateh Pirzada.  However, the Shashank Khaitan directorial was reportedly shelved due to script issues. Now, veteran Malayalam actor Mohanlal’s upcoming film Vrushabha will finally mark Shanaya's first movie as an actor."
  },
  {
    id: 33,
    title: 'Kohrra review: Sudip Sharma juggles between slow-burn and sledgehammer',
    post_date: 'July 15 2023',
    genre: 'Hollywood',
    ref: 'https://www.hindustantimes.com/entertainment/web-series/kohrra-review-sudip-sharma-juggles-between-slow-burn-and-sledgehammer-101689061883883.html',
    thumb: 'https://www.hindustantimes.com/ht-img/img/2023/07/11/550x309/kohrra_1689062424521_1689062441901.jpg',
    description: "Kohrra is no Pataal Lok. It's not edgy or pacey. But that doesn't mean it's not engaging or hard-hitting. It simmers before it explodes every once in a while.",
    detail: "Remember Rachel Shelley from Lagaan? The British actor played Elizabeth Rusell in Ashutosh Gowariker's 2001 historical epic starring Aamir Khan. When I saw her first pop up in Sudip Sharma's new Netflix show Kohrra, I couldn't help but recall her lip-syncing to “No drop of rain, no glowing flame, Has ever been so pure, If being in love can feel like this, Then I'm in love for sure.” But the song faded as quickly as the joy of returning to India on her face. Her son is missing.  Kohrra, co-created and co-written by Sudip, Gunjit Chopra and Diggi Sisodia, and directed by Randeep Jha, is set in Punjab. Balbir Singh (Suvinder Vicky) and Garundi (Barun Sobti) are cops investigating the murder of Paul, the son of a local influential man, and the missing case of his best friend Liam, an NRI from the UK, son of Clara (Rachel Shelley).  Rachel Shelley, like us, realises very quickly that she is not in Lagaan. She's not a powerful white man's sister in British India. She's a hapless outsider in a state that runs on the nexus between powerful leaders and drug cartels.  Kohrra has shades of Abhishek Chaubey's Udta Punjab (2016), which was co-written by Sudip Sharma. The trailer may also give the impression that Kohrra is a fast-paced, thrilling ride like Sudip's Prime Video show Pataal Lok. But I suggest those expecting the same to manage their expectations: Kohrra is the slowest of slow burns. It takes more than an episode to warm up to its pace and its world. The pace still doesn't pick up, but the investment in certain characters does. The final reveal isn't worth pulling along, unless one's found a character to latch on to."
  },
  {
    id: 34,
    title: "Lock Upp: Chetan Hansraj evicted in five days for misbehaving with jailor; viewers say, 'don't mess with Karan Kundrra'",
    post_date: 'May 26 2023',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/web-series/lock-upp-chetan-hansraj-evicted-in-just-five-days-for-misbehaving-with-jailor-viewers-say-don-t-mess-with-karan-kundrra-101648280907379.html',
    thumb: 'https://images.hindustantimes.com/img/2022/03/26/550x309/karan_(2)_1648281728616_1648281739734.jpg',
    description: "Chetan Hansraj has become the fifth contestant to be eliminated from Lock Upp, after Swami Chakrapani Maharaj, Tehseen Poonawalla, Siddharth Sharma, and Babita Phogat.",
    detail: "Actor Chetan Hansraj has been evicted from Lock Upp just five days after his entry into the captivity-based reality show. Instead of being charge sheeted by his co-contestants during the elimination rounds or getting voted out by the viewers, Chetan was locked out of jail by the producers for misbehaving with jailor Karan Kundrra.  A promo of the show shared on the Instagram account of Alt Balaji on Saturday had shown Chetan breaking the rules of the prison. The post, that announced Chetan's eviction, was shared with the caption, 'Misbehaviour ko sirf dismissal milta hai yahan! @chetan_hansraj huye locked out (Misbehaviour is dismissed here, Chetan Hansraj is locked out, what do you think about it?)'  The video started with Anjali Arora saying the contestants get ready to take unnecessary actions after getting charge sheeted. Chetan then gets up and starts tampering with the rules written on a blackboard, amid warnings from his fellow contestants who say, 'Don't remove!' Kaaranvir Bohra can be heard saying, 'Chetan don't do this.'  However, Chetan erases a part of the word jailor on the background to make it read tailor. Then he reads the new sentence, 'Rules badalna tailor ki marji hai (tailor can change rules on his wishes).' As Kaaranvir Bohra asks Chetan why is he acting like this soon after telling the jailor that he is his fan, Chetan says, 'I don't give a f*** about their rules. I won't follow any rules, what can they do?'"
  },
  {
    id: 35,
    title: "Ekta Kapoor says Lock Upp host Kangana Ranaut is unbiased, has strong views: 'I don't agree with them'",
    post_date: 'April 22 2022',
    genre: 'Bollywood',
    ref: 'https://www.hindustantimes.com/entertainment/web-series/ekta-kapoor-says-lock-upp-host-kangana-ranaut-has-strong-views-i-don-t-agree-with-them-101650612100410.html',
    thumb: 'https://images.hindustantimes.com/img/2022/04/22/550x309/ANI-20220216252-0_1650612624212_1650612636872.jpg',
    description: "Ekta Kapoor has heaped praises on Kangana Ranaut and revealed why she was chosen as the host of Lock Upp. Though Ekta appreciated Kangana's strong views, she added that even she didn't agree with them sometimes",
    detail: "Ekta Kapoor, who is the producer of Lock Upp, has opened up about why she chose actor Kangana Ranaut as the host of the reality show. In a new interview, Ekta called Kangana non-biased and clutter-breaker. Ekta also said that Kangana Ranaut has strong views but at times, even she doesn't agree with them. Ekta cited mutual respect as 'the greatest reason we can work together'.  Ekta also said that she was looking for a female host for the show, which is 'missing in India'. Lock Upp features controversial celebrities locked up in a jail-like setup with basic amenities. It is currently streaming on ALTBalaji and MX Player.  In an interview with Quint, 'I thought of her two years ago. As the format was forming, I felt digital needs a shakeup, a clutter-breaker. And she's pretty much a clutter-breaker. And not only controversial, she's a clutter breaker. Thought process wise also. Secondly, I wanted to do a reality show with a female host. I feel that was missing in India. We don't take this female host seriously because we are very fitting in girls. Girls will come in the typical saree look and they will stand there and giggle...Women are doing that in a lot of other spheres but she's the right person to bring in for this thought that female host, female running the show and taking on a whole captive reality format forward.'  On working with Kangana, she said, 'I've done three films with her and I've had a great experience. I've known her to be pretty non-biased like if you see her now also with Munawar (Faruqui) and her, they get along famously on the show. That shows the non-bias is there. She won't go on a show and say, 'Ok I don't get along with this guy or his political beliefs so I'm not gonna like him on the show'. She comes in, she's pretty non-biased, she likes the person how he's playing his game and I love that about her. I knew that she's interesting. She has (her) points of views and they're pretty strong and that sometimes rattles a lot of people, sometimes I don't even agree with them but mostly there's mutual respect and that's the greatest reason we can work together.'"
  },
  {
    id: 36,
    title: '',
    post_date: '',
    genre: 'Fitness',
    ref: '',
    thumb: '',
    description: "",
    detail: ""
  },
  {
    id: 37,
    title: '',
    post_date: '',
    genre: 'Fitness',
    ref: '',
    thumb: '',
    description: "",
    detail: ""
  },
  {
    id: 38,
    title: '',
    post_date: '',
    genre: 'Fitness',
    ref: '',
    thumb: '',
    description: "",
    detail: ""
  },
  {
    id: 39,
    title: '',
    post_date: '',
    genre: 'Fitness',
    ref: '',
    thumb: '',
    description: "",
    detail: ""
  },
  {
    id: 40,
    title: '',
    post_date: '',
    genre: 'Fitness',
    ref: '',
    thumb: '',
    description: "",
    detail: ""
  },
];

export const ContextData = createContext(data);
